### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by semel1** [google/dynamic-video-depth#8]
Upon running : 
bash ./experiments/davis/train_sequence.sh 0 --track_id dog
Got an error:
File "train.py", line 106
 str_warning, f'ignoring the gpu set up in opt: {opt.gpu}. Will use all gpus in each node.')
SyntaxError: invalid syntax

**Comment by ZoZomk6** [comment]
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 11, in <module>
    from tools.ddos import DDOSTools
  File "/usr/share/doc/hackingtool/tools/ddos.py", line 29
    "sudo", "python3 ddos", method, url, socks_type5.4.1, threads, proxylist, multiple, timer])
                                                    ^
SyntaxError: invalid syntax
I don't know what to do
